[package]
name = "mc-server-management-api"
version = "0.1.0"
edition = "2021"
rustflags = ["-C", "warnings=off"]

[dependencies]
lazy_static = "1.4.0"
serde = "1.0.188"
serde_json = "1.0.107"

[dev-dependencies]
uuid = {version = "1.4.1", features = ["v4", "fast-rng"]}
